AddEventHandler("vorp:SelectedCharacter", SelectedCharacterHandler)
AddEventHandler("vorp:initNewCharacter", SelectedCharacterHandler)
AddEventHandler("playerDropped", PlayerDroppedHandler)
AddEventHandler("onResourceStart", ResourceStartHandler)
AddEventHandler("vorp:playerJobChange", JobChangeHandler)
RegisterNetEvent("vorp_core:Server:OnPlayerDeath", DeathHandler)
AddEventHandler("vorp_core:Server:OnPlayerRevive", RespawnHandler)
AddEventHandler("vorp_core:Server:OnPlayerRespawn", RespawnHandler)
